// src/data/cities.js
export const cities = [
  { name: "London", country: "UK" },
  { name: "Paris", country: "France" },
  { name: "Tokyo", country: "Japan" },
  { name: "New York", country: "USA" },
  { name: "Phnom Penh", country: "Cambodia" },
  { name: "Beijing", country: "China" },
  { name: "Moscow", country: "Russia" },
  { name: "Sydney", country: "Australia" },
  { name: "Berlin", country: "Germany" },
  { name: "Rome", country: "Italy" },
  { name: "Madrid", country: "Spain" },
  { name: "Seoul", country: "South Korea" },
  { name: "Singapore", country: "Singapore" },
  { name: "Dubai", country: "UAE" },
  { name: "Toronto", country: "Canada" },
  { name: "Mexico City", country: "Mexico" },
  { name: "Rio de Janeiro", country: "Brazil" },
  { name: "Cape Town", country: "South Africa" },
  { name: "Istanbul", country: "Turkey" },
  { name: "Delhi", country: "India" },
  { name: "Kuala Lumpur", country: "Malaysia" },
  { name: "Hanoi", country: "Vietnam" },
  { name: "Athens", country: "Greece" },
  { name: "Lisbon", country: "Portugal" },
  { name: "Buenos Aires", country: "Argentina" },
  { name: "Lagos", country: "Nigeria" },
  { name: "Cairo", country: "Egypt" },
  { name: "Jakarta", country: "Indonesia" },
  { name: "Honolulu", country: "USA" }
];
